#!/bin/sh

# Get message
MSG=$(cat "${1:?Missing commit message file}")

echo "runing pre commit..."
## Getting the right version of scripts
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPTS_BIN=$CURRENT_DIR/scripts/bin_mac # defaults to mac

if [[ $(uname -s) == "Linux" ]]; then
  Info "Linux platform, setting the configs to linux..."
  SCRIPTS_BIN=./scripts/bin_lnx # sets to linux
fi

${SCRIPTS_BIN}/semver --comment "${MSG}" >/dev/null

ERR=$?
if [[ $ERR != 0 ]]; then
    echo "your commit message does not satisfy the semantic version requirements."
    echo "commit message: ${MSG}"
    exit 1
fi
